package router

import (
	"golang-mygram/controllers"
	"golang-mygram/middlewares"
	"net/http"

	"github.com/gin-gonic/gin"

	_ "golang-mygram/docs" // docs is generated by Swag CLI, you have to import it.

	ginSwagger "github.com/swaggo/gin-swagger"

	swaggerfiles "github.com/swaggo/files"
)

// @title Mygram (Instagram Clone)
// @version 1.0
// @description This is an Instagram Clone for CRUD-ing photos, and comments among users
// @termsOfService http://swagger.io/terms/
// @contact.name API Support
// @contact.email soberkoder@swagger.io
// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html
// @host localhost:8080
// @BasePath /
func StartApp() *gin.Engine {
	r := gin.Default()

	// Read homepage content
	r.GET("/", func(c *gin.Context) {
		c.JSON(http.StatusOK, "Mygram (Instagram Clone) by gunturajip")
	})

	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerfiles.Handler))

	guestRouter := r.Group("/users")
	{
		// Register user
		guestRouter.POST("/register", controllers.UserRegister)

		// Login user
		guestRouter.POST("/login", controllers.UserLogin)
	}

	r.Use(middlewares.Authentication())
	{
		photoRouter := r.Group("/photos")
		{
			// Get all photos
			photoRouter.GET("/", controllers.GetPhotos)

			// Post photo
			photoRouter.POST("/", controllers.CreatePhoto)

			// Get photo by id
			photoRouter.GET("/:photoID", controllers.GetPhoto)

			// Update photo by id
			photoRouter.PUT("/:photoID", middlewares.PhotoAuthorization(), controllers.UpdatePhoto)

			// Delete photo by id
			photoRouter.DELETE("/:photoID", middlewares.PhotoAuthorization(), controllers.DeletePhoto)
		}

		commentRouter := r.Group("/comments")
		{
			// Get all comments
			commentRouter.GET("/", controllers.GetComments)

			// Post comment
			commentRouter.POST("/", controllers.CreateComment)

			// Get comment by id
			commentRouter.GET("/:commentID", controllers.GetComment)

			// Update comment by id
			commentRouter.PUT("/:commentID", middlewares.CommentAuthorization(), controllers.UpdateComment)

			// Delete comment by id
			commentRouter.DELETE("/:commentID", middlewares.CommentAuthorization(), controllers.DeleteComment)
		}

		socialMediaRouter := r.Group("/socialmedia")
		{
			// Get all social media
			socialMediaRouter.GET("/", controllers.GetSocialMedias)

			// Post social media
			socialMediaRouter.POST("/", controllers.CreateSocialMedia)

			// Get social media by id
			socialMediaRouter.GET("/:socialMediaID", controllers.GetSocialMedia)

			// Update social media by id
			socialMediaRouter.PUT("/:socialMediaID", middlewares.SocialMediaAuthorization(), controllers.UpdateSocialMedia)

			// Delete social media by id
			socialMediaRouter.DELETE("/:socialMediaID", middlewares.SocialMediaAuthorization(), controllers.DeleteSocialMedia)
		}
	}

	return r
}
